### ISSUE TITLE
Deleting non-confirmed txs

### ISSUE THREAD

**Issue by wchancao** [akumaigorodski/wallet#118]
SBW should auto delete txs that were not mined and didn't got a confirmation. Instead, it keeps the tx in the tx list as "waiting" but i confirmed that the tx is not in my mempool or others mempools at all. And there's no option to delete it when swiping it to the right.

**Comment by wchancao** [comment]
But SBW should follow what the electrum server that is connected to is telling to it, right? Following this logic, if the tx isn't in that electrum server index, SBW should not show it, right?

**Comment by btcontract** [comment]
This is not how it works: we can only know that some tx is pending and later got confirmed, but not that it failed because it got excluded from local mempool, there is no such event.

**Comment by wchancao** [comment]
So, unconfirmed txs will be shown for the eternity in SBW? Im not an expert at all, but how does Electrum Wallet manages this cases? Because Electrum managed to delete or not show this tx, and SBW does show it, both wallets conected to the same electrs.

**Comment by btcontract** [comment]
Perhaps Electrum Wallet was restored after tx has been excluded from mempool? One way to get it removed is remove SBW data and restore it from recovery phrase: tx will then not bee seen but still may pop up confirmed later if some miner does include it in mempool.

**Comment by wchancao** [comment]
No, Electrum Wallet was not restored after that tx was excluded from mempool. Dont know if it matters but its a Watch Only wallet we are talking about.

**Comment by btcontract** [comment]
> Watch Only wallet we are talking about

Should not matter but anyway I want to emphasize that there is no such thing as failed tx once it has been broadcasted, marking such a tx as failed does not reflect what is really going on (it may still be pending somewhere).

If the goal is to get a tx to recipient then it should be RBF-bumped, if the goal is to get it back reliably then it should be RBF-cancelled, otherwise it's in state of uncertainty and it may be unsafe to rely on that.

**Comment by wchancao** [comment]
How about if this tx cant be RBF or CPFP?

**Comment by btcontract** [comment]
I can add a "reset wallet" button which would clear its state and make it resync from scratch. This is not a panacea since a pending tx may pop up again if it's still pending somewhere but may be used in such edge cases.
