### ISSUE TITLE
Where is the testnet wallet?

### ISSUE THREAD

**Issue by purpurato** [akumaigorodski/wallet#141]
I remember downloading the testnet wallet from the store but I don't see it there anymore. There aren't many testnet wallets around but it's pretty useful to try them before going mainnet.

**Comment by btcontract** [comment]
Testnet version has been removed from Play store because there were a few successful scam attempts where users were lead to believe that their testnet wallet is actually a mainnet one. Guess I can proceed with publishing of testnet APK in releases here instead.

**Comment by purpurato** [comment]
Yes, the APK signed should be enough, no need for Play Store. 
Looking forward to it.
