### ISSUE TITLE
Question about iOS support

### ISSUE THREAD

**Issue by MWICA** [akumaigorodski/wallet#145]
Is there planned support for an iOS version? Is there a reason why many open source applications generally don't support iOS? Although I am personally not a fan of iOS I know many people do use it and want to try out lightning network or use lightning network for receiving payments. Some business owners use iphone.

**Comment by Rooman95** [comment]
Dear sir.

We are requested to you please we send the all payment I have no iPhone
Mobile so please I need your support. iam transferring the payment purchase
the iPhone Mobile 13 Pro Max and Delivered my home Address please asked me
Yes or No.

Thanking you.
