### ISSUE TITLE
Is Thunderbolt fork android app `com.thunderbolt.wallet` scam or legit?

### ISSUE THREAD

**Issue by emanuelb** [akumaigorodski/wallet#146]
Android app "Thunderbolt - Bitcoin and Lightning Wallet"
https://play.google.com/store/apps/details?id=com.thunderbolt.wallet
website:
https://thunderboltwallet.com/
is look like BLW/SBW websites:
https://sbw.app/
https://lightning-wallet.com/ which is unavailable, see related issue: #143

it's says open-source while didn't found code for "com.thunderbolt.wallet" app, version on play-store is "1.0.3" from: "August 29, 2021"
it wasnt reviewed by walletscrutiny yet as it's has few users (100+ installs) https://walletscrutiny.com/android/com.thunderbolt.wallet/

license of this repo is Apache, so closed-source fork is "ok" at least according to license.
Feel free to investigate more and report the app to play-store if it's scam.

**Comment by fiatjaf** [comment]
A wallet that copies everything including the website and blog posts from SBW -- and even keeps the links to F-Droid and APK, changes only the link to the Android app?

That's definitely a **scam** that will steal your money.

**Comment by Giszmo** [comment]
We will update WalletScrutiny accordingly, pointing to this issue.
