### ISSUE TITLE
LN payment stuck in "preparing"

### ISSUE THREAD

**Issue by iljah** [akumaigorodski/wallet#152]
Tried several times to pay different bitrefill invoices with lightning but they never go past "preparing". Using 2.4.27, also tried restarting both wallet and phone without effect. Channel opened to bitrefill server. Sharing latest try gives debug info: local failure: not-retrying-no-details

**Comment by fiatjaf** [comment]
You only have one channel with Bitrefill, no other channels? This only happens with Bitrefill invoices, not with other invoices?

**Comment by iljah** [comment]
I had another channel with insufficient balance for paying above invoices. Both channels were to bitrefill but different nodes. Haven't tried with other invoices and can't test anymore as I closed both channels.

**Comment by fiatjaf** [comment]
I think you might have been trying to send the payment through an unresponsive channel, but I don't know. This could be better handled anyway. I believe the payment will stop after a while an give you a timed-out message though.

**Comment by iljah** [comment]
It timed out after about 30 mins which is what bitrefill seems to use. Manually removing the payment after couple of minutes didn't seem to work completely since trying to pay the same invoice again resulted in something like: value already in flight.

**Comment by iljah** [comment]
Note that I opened the channel with enough sendable balance just before trying to send through it. Perhaps the channel which didn't have enough balance was unresponsive but wallet was trying to negotiate with it first?..
