### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by pony-montana** [akumaigorodski/wallet#166]
Hi, here my personal missing features list:
- entering HW by texting, now only possible by qr-code scan.
- seed passphrase (13th word) support.
- sign/verify messages

**Comment by akumaigorodski** [comment]
Is there any standard way for signing and verifying of messages?

**Comment by pony-montana** [comment]
I found two useful discussion summurizing the state of things:
https://github.com/sparrowwallet/sparrow/issues/39
https://github.com/spesmilo/electrum/issues/3861

So there are two competing working standard, the "trezor" and the "electrum" one, and a complicated bip322 adopted by no one.

I also add that in the wild, the way bluewallet sign and verify is consider a sort of standard because is available on all mobile platform and is newbie-friendly, so business that work with this features consider to base it on bluewallet (I don't know what standard it implements).

Its a wild west today, so I dont know what could be the right way to implement this feature, or even if it worth the effort.
