### ISSUE TITLE
apk not valid, doesnt install

### ISSUE THREAD

**Issue by pony-montana** [akumaigorodski/wallet#167]
Hi, the 2.5.2 version from github release doesnt install. It says "apk not valid".
Trying to install it with an app-manager-software shows me the more detailed log: "Package /data/app/~~X8PqPe9VhDuVF7lUqOa5jA==/com.btcontract.wallet-TJHR7x1MER4UlYTf0eroGA==/base.apk code is missing"

**Comment by akumaigorodski** [comment]
Indeed, thanks for the heads up. I've uploaded another version and made sure it works.
