### ISSUE TITLE
Unable to connect on electrum server over tor

### ISSUE THREAD

**Issue by onlineapps-cloud** [akumaigorodski/wallet#182]
Hi, when i want to configure electrum wallet over tor, i get error like my address contain 552 bytes, and maximum allowed is 512 bytes , can you increase URL lenght to 1024 bytes on example? to have possibility to connect on electrum over tor, thanks, best whishes.

**Comment by akumaigorodski** [comment]
Hi, can you please provide a TOR address (or DM at anton.kumaigorodskiy@outlook.com)? That should help with debugging.

**Comment by onlineapps-cloud** [comment]
hi, i wrote to your email.

**Comment by onlineapps-cloud** [comment]
hi, any news about onion address support?

**Comment by akumaigorodski** [comment]
Hey, I'm way too busy with other things currently, sorry for not mentioning this right away. I plan to get back to this and overall wallet development but don't yet know when this will happen.

**Comment by akumaigorodski** [comment]
In-app Tor support has been dropped, please use Orbot.
