### ISSUE TITLE
2 security issue + apk is like a malicious

### ISSUE THREAD

**Issue by yousefebrahimi0** [akumaigorodski/wallet#183]
Why seeing these critical errors?!
Please check the latest version with virustotal:

https://www.virustotal.com/gui/file/255a6fc14d8c900d92f9a707c73b50e2f1668ed020f2f23da3af50ca6fa7dd05/detection

**Comment by akumaigorodski** [comment]
I have no idea and currently no time to investigate. This app is provably reproducible so the code you see in this repo is the code which runs on your phone. If someone feels like it then please investigate and publish results.
