### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [akumaigorodski/wallet#191]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8017894651 com.google.android.play:review is not FOSS. And the new added play-services-auth is also not free. Could you please provide a falvor for F-Droid without it? Thanks!

**Comment by akumaigorodski** [comment]
I'm sorry but I don't have time for this. It's fine if someone is willing to commit to maintain such a feature branch.

**Comment by licaon-kter** [comment]
maybe update https://sbw.app/ too as the proprietary Google libs that are now included are secret and can't be publicly verifiable since there's no source code :shrug:

**Comment by linsui** [comment]
OK, I removed it with a downstream patch. :)
