### ISSUE TITLE
Add f-droid download logo

### ISSUE THREAD

**Issue by onlineapps-cloud** [akumaigorodski/wallet#193]
hi, please add f-droid logo on f-droid sbw page
**`on github`**

![image](https://github.com/user-attachments/assets/7837c550-8f37-405d-8b50-1c6280ee6d35)
**`and on https://sbw.app`** 

![image](https://github.com/user-attachments/assets/4896729e-05de-4611-8a4b-387528257b9d)

**Because right now i have filling that someone (not you) published a fake app on f-droid. So i don't understand why f-drod not present as safe download page for your app? best regards.**

**Comment by akumaigorodski** [comment]
It's fine, it was me. I've added google auth library which I plan to utilize in future and this made an app incompatible with f-droid standards. They have stopped publishing updates and I've removed f-droid links.

**Comment by akumaigorodski** [comment]
Yes, it will. All that auth stuff is optional and can be totally disregarded.
