### ISSUE TITLE
f-droid latest version and github release is different?

### ISSUE THREAD

**Issue by onlineapps-cloud** [akumaigorodski/wallet#194]
hi, on [f-droid sbw page](https://f-droid.org/en/packages/com.btcontract.wallet/)  Version  is 2.5.9 (111) Added on Oct 09, 2024.
But on github version is 2.6.
Release date on f-droid is same as on github.
So, these version is same or not?

**Comment by akumaigorodski** [comment]
It's probably the result of this: https://github.com/akumaigorodski/wallet/issues/191
