### ISSUE TITLE
Use distributionSha256Sum for verification of downloaded Gradle & Upgrade Gradle+Gradle-Plugin

### ISSUE THREAD

**Issue by emanuelb** [akumaigorodski/wallet#57]
1. Upgrade Gradle to 7.2 (Currently used 5.4.1)

https://github.com/btcontract/wallet/blob/59223ae0aee32c8c5ae0a76439fd531f87ad3253/gradle/wrapper/gradle-wrapper.properties#L6

Latest version of gradle is 7.2 https://gradle.org/releases/, download link:
https://services.gradle.org/distributions/gradle-7.2-all.zip

upgrade can be done with command: (in general it's better then manual edit as it's also upgrading gradle scripts if their is update to them)
`./gradlew wrapper --gradle-version 7.2`

2. Add `distributionSha256Sum` to `gradle-wrapper.properties` file

more info: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification
such as: (checksum taken from: https://gradle.org/release-checksums/)
`distributionSha256Sum=a8da5b02437a60819cad23e10fc7e9cf32bcb57029d9cb277e26eeff76ce014b`

3. Upgrade Gradle Plugin

latest stable version is: 7.0.1
https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google

used version is: 3.5.4
https://github.com/btcontract/wallet/blob/3b240e408ad8011f60dab7f3248ade306de301b6/build.gradle#L8

This will require probably some code changes as well to make the app compiled with the newest gradle version, even if the latest version can't be used yet, it's still better to use newer versions if possible.

**Comment by btcontract** [comment]
The main blocker for this is `gradle-android-scala-plugin` which lags behind. The plan is to fork it and update to support latest Gradle version after I'm done with higher priority tasks.
