### ISSUE TITLE
Remove foreground notification if related unfulfilled incoming payment has been removed from db

### ISSUE THREAD

**Issue by akumaigorodski** [akumaigorodski/wallet#73]

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/b8d77771b2447b273f7fbf3509b1b7cf1fe264ac.

**Comment by btcontract** [comment]
This needs more careful handling since foreground notification will also be there when we have active routed payments, we don't want to occasionally remove it by deleting a payment card.
