### ISSUE TITLE
Suggestion: Prompt User to Activate Tor if Tor Channel required for payment.

### ISSUE THREAD

**Issue by HamishMacEwan** [akumaigorodski/wallet#78]
It's sometimes better to not bring up Tor for unrelated activities, but if the user requests Tor is made mandatory and enforced with a prompt at start up.

Recently a payment required my Tor channel to pay, and the payment failed.  Eventually the user failure was realised, but could SBW prompt the user if Tor is essential.

It was only necessary to bring up Orbot, select SBW from there and retry the payment, very nice.

**Comment by btcontract** [comment]
Makes sense indeed.
